apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.releaseName }}-frontend
  labels:
    app: {{ .Values.global.releaseName }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.global.releaseName }}-frontend